export const parseCardsToServer = ({
  skillsHave,
  ccRelationshipWithColleague,
  firstName,
  lastName,
  ccDescByColleagues,
  skillsTasksCollab,
  skillsRecommend,
  company,
  skillsTasksAuto,
  skillsRolesInCompany,
  skillsLearned,
  ccCompetitiveness,
  tobeContacted,
  ccRelationshipWithMgr,
  nationality,
  position,
  ccWorkingApproach,
}) => ({
  skills_have: skillsHave,
  cc_relationship_with_colleague: ccRelationshipWithColleague,
  first_name: firstName,
  last_name: lastName,
  cc_desc_by_colleagues: ccDescByColleagues,
  skills_tasks_collab: skillsTasksAuto,
  skills_recommend: skillsRecommend,
  company: company,
  skills_tasks_auto: skillsTasksAuto,
  skills_roles_in_company: skillsRolesInCompany,
  skills_learned: skillsLearned,
  cc_competitiveness: ccCompetitiveness,
  tobe_contacted: tobeContacted,
  cc_relationship_with_mgr: ccRelationshipWithMgr,
  nationality: nationality,
  position: position,
  cc_working_approach: ccWorkingApproach,
});

export const parseCardsFromServer = ({
  skills_have,
  cc_relationship_with_colleague,
  first_name,
  last_name,
  cc_desc_by_colleagues,
  name,
  skills_tasks_collab,
  skills_recommend,
  company,
  skills_tasks_auto,
  skills_roles_in_company,
  skills_learned,
  cc_competitiveness,
  tobe_contacted,
  cc_relationship_with_mgr,
  nationality,
  position,
  id,
  cc_working_approach
}) => ({
  skillsHave: [skills_have],
  ccRelationshipWithColleague: cc_relationship_with_colleague,
  firstName: first_name,
  lastName: last_name,
  ccDescByColleagues: cc_desc_by_colleagues,
  name: name,
  skillsTasksCollab: [skills_tasks_collab],
  skillsRecommend: [skills_recommend],
  company: company,
  skillsTasksAuto: [skills_tasks_auto],
  skillsRolesInCompany: skills_roles_in_company ? skills_roles_in_company.split(',') : [''],
  skillsLearned: [skills_learned],
  ccCompetitiveness: cc_competitiveness,
  tobeContacted: tobe_contacted,
  ccRelationshipWithMgr: cc_relationship_with_mgr,
  nationality: nationality,
  position: position,
  id: id,
  ccWorkingApproach: cc_working_approach
});
